name: Update HAYQ Bot

on:
  workflow_dispatch:
  schedule:
    - cron: '*/10 * * * *' # ստուգում է GitHub repo–ում նոր commit–երը 10 րոպեը մեկ

jobs:
  update-hayq-bot:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Pull latest changes and install dependencies
        run: |
          cd ./projects/hayq-node-bot
          npm install
