name: Manage Bots

on:
  workflow_dispatch:    # թույլ է տալիս ձեռքով գործարկել workflow
  schedule:
    - cron: '*/10 * * * *'  # ստուգում 10 րոպեը մեկ

jobs:
  update-and-run-bots:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: List all projects
        id: list_projects
        run: |
          mkdir -p ./projects
          echo "Listing all bot projects..."
          ls -1 ./projects > bot_list.txt
          cat bot_list.txt
          echo "BOT_LIST<<EOF" >> $GITHUB_ENV
          cat bot_list.txt >> $GITHUB_ENV
          echo "EOF" >> $GITHUB_ENV

      - name: Manual approval for new projects
        uses: hmarr/auto-approve-action@v2
        if: ${{ always() }}
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Run Python bots
        run: |
          for folder in $(cat bot_list.txt); do
            if [ -f "./projects/$folder/auto_push.py" ]; then
              echo "Running Python bot in $folder"
              python3 "./projects/$folder/auto_push.py"
            fi
          done

      - name: Run Node.js bots
        run: |
          for folder in $(cat bot_list.txt); do
            if [ -f "./projects/$folder/bot.js" ]; then
              echo "Running Node.js bot in $folder"
              cd "./projects/$folder"
              npm install
              node bot.js &
              cd ../../
            fi
          done
